dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
 
 addons:
  sonarcloud:
    organization: "gii-is-dp1"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
script:
  # other script steps might be done before running the actual analysis
  - mvn test -Dspring-boot.run.profiles=mysql-travis
  - sonar-scanner
