dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
 
addons:
  sonarcloud:
    organization: "gii-is-dp1" 
    token:
      secure: c7622545540da9fa8d297c47ce5e9be3a66da2d3
script:
  # other script steps might be done before running the actual analysis
  - mvn test -Dspring-boot.run.profiles=mysql-travis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gii-is-DP1_dp1-2020-g1-12
