dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
 
script:
  # other script steps might be done before running the actual analysis
  - mvn test -Dspring-boot.run.profiles=mysql-travis
