dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE petclinic;'
addons:
  sonarcloud:
    organization: "gii-is-dp1"
    token:
      secure: 3ffa109593a9fd216a5c8cf1a210c65451b49a63 # encrypted value of your token

script:
  - mvn test -Dspring-boot.run.profiles=mysql-travis
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gii-is-DP1_dp1-2020-g2-02
